
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
